### PR TITLE
CSS classes for the landing page

### PR DESCRIPTION
**Pull request by MirisWisdom**
**Describe this PR:**
This PR introduces CSS classes to the landing page markup. The BEM convention is followed to ensure modularity, readability and maintainability. One of the styling developers should develop the CSS classes to represent the concept UIs and follow the naming convention. If that can't be done, I will take care of directly developing the Sass without any CSS prototypes.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Refactor
- [ ] Style
- [ ] Build-related changes
- [x] Other, please describe: Markup

**Other information:**
The following list shows the introduced classes and their descriptions and serves as a guideline for the stylesheets.

**Header**
- `header` - Container for page header elements, particularly the navigation bar.
  - `header--landing` - Modifier: Small in height, transparent.
- `header__nav` - Container for navigational items. Left side is for page links, right is for user links such as authentication and registration.
- `nav__items` - Items list container for the links on the navigation bar.
  - `nav__items--left` - Modifier: Positioned on the left side of the navbar.
  - `nav__items--right` - Modifier: Positioned on the right side of the navbar.
- `nav__item` - Container for the `<a>` element. This should define the spacing between the links.
- `link` - Generic class for `<a>` elements. The main property should be `text decoration: none;`
  - `link--white` - Modifier: White foreground colour for the link.
  - `link--button` - Modifier: Border around the link.
  - `link--filled` - Modifier: Link has background colour.

**Landing section**
- `section` - Generic container for non-header/footer data.
- `section__landing` - Container which occupies the screen. Its height should be: screenHeight - (headerHeight + footerHeight)
- `landing__introduction` - Container for the introductory text.
- `landing__invitation` - Container for the invitation button.
- `title` - Generic attribute for titles. Should probably have a margin & padding of 0.
  - `title--big` - Modifier: Bigger title; maybe 36-48pt?
  - `title--bold` - Modifier: Bold title.

**Social media section**
- `landing__social-links` - Container for the social media links text & group.
- `text` - Generic text element.
  - `text--grey` - Modifier: Colour of the text is grey.
- `social-links__items` - Container group for the social media links.
- `social-item` - Container for the `<a>` element. Again, this should define the spacing between the links.
- `icon` - Class which defines the size and border radius of an icon. Might want to use the `content` CSS attribute to define the respective social media website's icon.

### CODE REVIEW

**Comment by MirisWisdom** [comment]
Once this PR is merged, @WEBhicham can start developing the stylesheets in a new branch and PR. If that is not possible, I will take care of designing the stylesheets. Let me know how we should proceed with this!

**Review by lap00zza — COMMENTED** [review]
For multiple words what is better?  `_` or `-`
What I mean is: `social_links` or `social-links`

**Comment by WEBhicham** [comment]
social_links.
sometimes php or js wil take - als actuel minus.

**Comment by MirisWisdom** [comment]
I've looked into some examples, it turns out that `-` is used instead of `_`. I will update the class names now.

**Review by Swardu — APPROVED** [review]

**Review by lap00zza — APPROVED** [review]

**Comment by lap00zza** [comment]
This is ready for merge. @yumiris remove the `WIP` when you are done.

**Comment by MirisWisdom** [comment]
Ready!

**Pull request merged**
