### PR TITLE
Implementing SASS & Registration Page Style Updates

### PR DESCRIPTION
**Pull request by MirisWisdom**
The pull request will introduce the following changes:
- The CSS files added in https://github.com/GitHugop/AnimeScreen/commit/80450718ec7a95964fc25ac934e6bb2e13fb0dd7 have been converted to SASS files in the `assets/sass` folder.
- Said CSS files have been restructured for improved consistency and maintainability.
- Styling has been tweaked a bit, including the shadow's opacity being reduced.
- The registration form combined the style in @densityx's concept UI and @WEBhicham's compact design.
- Typo fixes and resolving naming + formatting inconsistencies.
- Organisation of code based on partials.
- BEM convention across the code.
- Ignoring the `assets/css` folder as compiled code goes there.

### CODE REVIEW

**Comment by MirisWisdom** [comment]
The registration form has been refined. The following image compares the old style with the new style.
New registration form look

**Review by lap00zza — APPROVED** [review]
Hi. Overall a very good commit. I have the following 2 suggestions that can be introduced at a later date.

1. Using BEM (https://css-tricks.com/bem-101/). This helps keep the structure of the SASS very clean.
2. Maybe add in auto prefixer to the toolchain somehow. Without that all the browser quirks have to be handled manually.

**Comment by MirisWisdom** [comment]
@lap00zza 

The code for the registration form have been separated into partials which are reusable across the website. I've further integrated the BEM convention into the code-base. Regarding autoprefixing, that's usually something which gets taken care off automatically during deployment.

Let me know what you think of the updates! Any suggestions will be taken into consideration.

**Review by lap00zza — APPROVED** [review]
I love the partials approach. Looks all good from my side, This is ready for merge.

**Review by Swardu — APPROVED** [review]

**Comment by MirisWisdom** [comment]
A few changes have been made to the registration form:
- Removed Facebook registration button as per @GitHugop's request.
- Error message as per @lap00zza's request.
- More compact design as per people's feedback.

screen shot 2017-06-18 at 01 55 33

Let me know if this is all good.

**Comment by Swardu** [comment]
Looks great. We probably should remove the "Name" field, since it might confuse users, and set username as default display name. They can change it later.

**Comment by MirisWisdom** [comment]
@GitHugop the `Name` textfield has been removed!

Other commits have been... committed... to make the form:
- Smaller in height/more compact. This should keep (most) people happy.
- Flexible with adding/removing elements by discarding the fixed height property. It expands/shrinks based on the contents.

Oh dear, we're really going over the line with the objective of this pull request.

**Comment by densityx** [comment]
@yumiris Remove the "Invalid password/email/username" part, I assume that's validation
I am planning something else for that one

And please add additional padding (between the logo and etc) like how it look on the design

The form should have this shadow
```
box-shadow: 0 0 6px 1px rgba(208,208,208,0.50);
```

The input type should use 'Light' weight font and color `#7C8495` with reduced font size

**Comment by MirisWisdom** [comment]
The suggested changes seem to make the form prone to being hard to read.

Additionally, the compact layout makes it fit much more easily on mobile screens.

However, if you've got an additional design in mind, raise a new Issue and I'll take a look! :)

**Pull request merged**
